{
 "title": "Edge server TF",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(edge_server_cpu_for_60)", "legendFormat": "Total" },
    { "expr": "edge_server_cpu_for_60", "legendFormat": "{{pod}} cpu" }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(edge_server_request_rate_for_30)",
     "legendFormat": "Sum"
    },
    {
     "expr": "sum by (pod) (\n  sum by (pod, status) (\n    edge_server_request_rate_for_30\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "expr": "sum(edge_server_memory)", "legendFormat": "Total" },
    {
     "expr": "sum  by (pod) (edge_server_memory)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(edge_server_latency_for_30)",
     "legendFormat": "Average"
    },
    { "expr": "edge_server_latency_for_30", "legendFormat": "{{pod}} average" }
   ]
  },
  {
   "title": "Number of edge-server pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "edge_server_pod_count", "legendFormat": "Total" }
   ]
  }
 ]
}